version: "3"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile 
    volumes: 
      - .:/app
    ports:
      - "20000:20000"
    depends_on: 
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
